server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Habilita soporte para SPA (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Redirecciona las peticiones de la API y Swagger al contenedor backend
    location /api {
        resolver 127.0.0.11 valid=30s;
        set $backend_upstream http://landing-backend-sistematizate:3000;
        proxy_pass $backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Habilita compresión Gzip para mejorar el rendimiento
    gzip on;
    gzip_vary on;
    gzip_min_length 10240;
    gzip_proxied any;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml application/javascript;
    gzip_disable "MSIE [1-6]\.";

    # Caché para recursos estáticos (Vite genera hashes únicos)
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
